### ISSUE TITLE
Invalid config for [sensor.files]: not a directory for dictionary value @ data['folder']. Got '/config/www/images'. (See ?, line ?). 

### ISSUE THREAD

**Issue by cooljimy84** [TarheelGrad1998/files#4]
So i already have a images folder in my www folder. If i use your example it gives me the above error. I i change the location in the config to /local/www/images (like my animated customs background uses) it also fails with the above error but saying /local/www/images.

If i put the full file path i.e. /home/homeassistant/.homeassistant/www/images it works fine.

System Health

Home Assistant Core Integration

version: 0.118.5
installation_type: Home Assistant Core
dev: false
hassio: false
docker: false
virtualenv: true
python_version: 3.8.0
os_name: Linux
os_version: 4.15.0-123-generic
arch: x86_64
timezone: Europe/London

Lovelace

dashboards: 1
mode: storage
views: 12
resources: 6

**Comment by TarheelGrad1998** [comment]
Hrm, it seems like your www folder is not under your config folder?  Based on your full path...

Are you able to access files from the web using that path?  I thought that www had to be under config (but may be mistaken)

**Comment by cooljimy84** [comment]
sorry to correct myself, i changed the user my instance runs under.
I've edited my above to show the correct user and location.

**Comment by TarheelGrad1998** [comment]
Right, but my assumption was that it would be more like:
   /home/homeassistant/.homeassistant/**config**/www/images

The main question is can you actually get an image from the web from there.  

To test this, copy any image in there, then try to hit it from a web browser:
https://YOUR-HA-URL/local/image.jpg

If you see the image, great, that should work.  Otherwise, you may have to move them under a /config directory for them to be displayed on the card.

For what it's worth, I'm working to change it to use the new media browser API, which will make it so this can be hosted anywhere, but I just haven't had time to put towards that.

**Comment by cooljimy84** [comment]
Yea, i think i was blindly following the instructions rather than looking at the example and adapting it.
Lack of coffee/sleep strike again.

Might be worth adding that test example to your guide.
